services:
    # Driverless main
    driverless:
        build: .
        image: pgr/dv
        container_name: dv
        stdin_open: true
        tty: true
        privileged: true
        network_mode: host
        ipc: host
        user: ros
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities:
                            - gpu
        environment:
            - DISPLAY=$DISPLAY
        volumes:
            - ./ws:/home/ros/ws
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            - /dev:/dev
            - /dev/video*:/dev/video*
    # Formula Student Driverless Simulator
    fsds:
        build: ./fsds
        image: pgr/fsds
        container_name: fsds
        stdin_open: true
        tty: true
        privileged: true
        network_mode: host
        user: fsdssim_user
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities:
                            - gpu
        environment:
            - DISPLAY=$DISPLAY
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:rw