version: "2.4"
services:
    ros2_pgr_dv:
        stdin_open: true
        tty: true
        volumes:
            - /dev:/dev
            - /dev/video*:/dev/video*
            - ./ws:/home/ros/ws
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
        environment:
            - DISPLAY
        ipc: host
        container_name: pgr_dv
        network_mode: host
        privileged: true
        user: ros
        image: ros2_pgr_dv
        build:
            dockerfile: Dockerfile


    fsds:
        build:
            context: RoboticsII-FSDS/docker/
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        privileged: true
        environment:
            - DISPLAY=$DISPLAY
            - QT_X11_NO_MITSHM=1
            - NVIDIA_DISABLE_REQUIRE=1
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=all
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
        network_mode: host
        container_name: $1
        image: fsds