version: "2.4"
services:
    driverless:
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        image: ros2_pgr_dv
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: pgr_dv
        privileged: true
        user: ros
        ipc: host
        network_mode: host
        environment:
            - DISPLAY=$DISPLAY
        volumes:
            - /dev:/dev
            - /dev/video*:/dev/video*
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            - ./ws:/home/ros/ws
    #
    fsds:
        stdin_open: true
        tty: true
        image: ros2_fsds
        build:
            context: ./fsds
            dockerfile: ./Dockerfile
        container_name: fsds
        privileged: true
        network_mode: host
        environment:
            - DISPLAY=$DISPLAY
            - QT_X11_NO_MITSHM=1
            - NVIDIA_DISABLE_REQUIRE=1
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=all
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:rw