/graphslam_backend_node:
  ros__parameters:
    rate: 0.4
    search_lidar_frame_num: 50
    search_radius: 100.0
    score_threshold: 0.3
    search_for_candidate_threshold: 15.0
    accumulate_distance_threshold: 100.0
    registration_method: "ICP"

    # Common Settings for Scan Matching
    max_iteration: 200
    omp_num_thread: 5
    #transformation_epsilon: 0.01 # NDT_OMP
    transformation_epsilon: 0.01 # GICP

    # NDT_OMP
    step_size: 0.1
    ndt_resolution: 1.0

    # FAST_GICP
    max_correspondence_distance: 2.0
    correspondence_randomness: 20
    max_optimizer_iteration: 20

    # GICP
    correspondence_distance: 2.0
    euclidean_fitness_epsilon: 1e-08
    ransac_iteration: 0
